### ISSUE TITLE
License declarations are missing

### ISSUE THREAD

**Issue by jengelh** [gerstrong/GsKit#2]
License declarations are mostly absent from GsKit. I suppose the intent is GPL2/GPL3, judging from the relation to CommanderGenius. However, since GsKit is a separate git repository and appears separately buildable, which in turn means Linux distributions can map it 1:1 into a independent package of their own too, declarations would help. It's mostly a cosmetical issue.
Implementing one of the following points should be sufficient:
* Adding a top-level file (as done in CommanderGenius), which then applies to all files which do not carry any different notice, or
* Adding a notice (e.g. using the (SPDX-License-Identifier notation)[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/license-rules.rst#n54]) to individual files

**Comment by gerstrong** [comment]
Okay, I added the same license file and modified it a bit. It should be okay now...

You can use GsKit for other projects. It bascially wraps SDL 1.2 and 2.0 and a bit of some helpers for file handling and strings basically...
